# Generated by Django 4.1.7 on 2023-04-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company_id',
            new_name='company',
        ),
    ]
