# Generated by Django 4.1.7 on 2023-04-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_info', '0002_rename_job_id_applications_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='company_name',
            new_name='company',
        ),
    ]
