# Generated by Django 4.1.7 on 2023-04-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_info', '0004_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminPanel',
        ),
    ]
