# Generated by Django 4.1.7 on 2023-04-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_info', '0005_rename_admin_adminpanel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='first_name',
            new_name='fullname',
        ),
    ]
